// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlgh7Qph57NH1hDRjVNwc63gZQ1kBqC-o',
    appId: '1:350575624727:web:f99875a5edc39a2a871252',
    messagingSenderId: '350575624727',
    projectId: 'zhaimer-e1774',
    authDomain: 'zhaimer-e1774.firebaseapp.com',
    storageBucket: 'zhaimer-e1774.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUOVON7M5RUrlfpPDP6_8hWQPym74ZcMo',
    appId: '1:350575624727:android:753198d03b54c1f9871252',
    messagingSenderId: '350575624727',
    projectId: 'zhaimer-e1774',
    storageBucket: 'zhaimer-e1774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvgYRMwviBT8FXmdNumQDIe0P5j32uLhA',
    appId: '1:350575624727:ios:17c05301b90aa260871252',
    messagingSenderId: '350575624727',
    projectId: 'zhaimer-e1774',
    storageBucket: 'zhaimer-e1774.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvgYRMwviBT8FXmdNumQDIe0P5j32uLhA',
    appId: '1:350575624727:ios:36f7e8b97098a58e871252',
    messagingSenderId: '350575624727',
    projectId: 'zhaimer-e1774',
    storageBucket: 'zhaimer-e1774.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
